apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    purpose: helm
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80  #target port
    nodeport: {{ .Values.service.nodePort }}
